# Configuration for Devsite to Hugo Converter

# Source repository settings
source_repo:
  owner: "bazelbuild"
  name: "bazel"
  branch: "master"
  path: "site/en"

# Hugo site settings
hugo:
  title: "Bazel Documentation"
  description: "Bazel Documentation in an easy to navigate format"
  baseURL: "https://bazel-docs-68tmf.ondigitalocean.app/"
  languageCode: "en-us"
  theme: "docsy"
  
# Content mapping - map Devsite sections to Hugo content types
content_mapping:
  start:
    type: "docs"
    weight: 10
    category: tutorials
  install:
    type: "docs"
    weight: 20
    category: how-to-guides
  run:
    type: "docs"
    weight: 30
    category: how-to-guides
  migrate:
    type: "docs"
    weight: 40
    category: how-to-guides
  release:
    type: "docs"
    weight: 50
    category: how-to-guides
  rules:
    type: "docs"
    weight: 60
    category: how-to-guides
  versions:
    type: "docs"
    weight: 70
    category: reference
  concepts:
    type: "docs"
    weight: 80
    category: explanation
  basics:
    type: "docs"
    weight: 90
    category: explanation
  tutorials:
    type: "docs"
    weight: 100
    category: tutorials
  build:
    type: "docs"
    weight: 110
    category: how-to-guides
  configure:
    type: "docs"
    weight: 120
    category: how-to-guides
  extending:
    type: "docs"
    weight: 130
    category: explanation
  external:
    type: "docs"
    weight: 140
    category: explanation
  remote:
    type: "docs"
    weight: 150
    category: explanation
  query:
    type: "docs"
    weight: 160
    category: reference
  reference:
    type: "docs"
    weight: 170
    category: reference
  community:
    type: "community"
    weight: 200
    category: reference
  contribute:
    type: "community"
    weight: 210
    category: reference
  about:
    type: "about"
    weight: 300
    category: reference
# CSS conversion settings
css_conversion:
  convert_to_scss: true
  preserve_custom_properties: true
  minify: false

# GitHub Actions settings
github_actions:
  listener_workflow_name: "bazel-listener"
  generator_workflow_name: "hugo-site-generator"
  dispatch_event_type: "bazel-docs-updated"

# Logging settings
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Conversion settings
conversion:
  preserve_original_structure: false
  generate_toc: true
  convert_internal_links: true
  validate_links: true
  
# File patterns to include/exclude
file_patterns:
  include:
    - "*.md"
    - "*.yaml"
    - "*.yml"
    - "*.css"
    - "*.png"
    - "*.jpg"
    - "*.jpeg"
    - "*.gif"
    - "*.svg"
  exclude:
    - "BUILD*"
    - "*.bazel"
    - "*.bzl"
    - ".git/**"
    - "node_modules/**"
