services:
  hugo:
    build: .
    container_name: bazel_docs
    ports:
      - "1313:1313"
    volumes:
      - .:/app
    entrypoint: [""]
    command: hugo server --bind=0.0.0.0 --baseURL=http://localhost:1313 --watch --disableFastRender
