[project]
name = "bazel_docs"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "click>=8.2.1",
    "gitpython>=3.1.44",
    "jinja2>=3.1.6",
    "markdown>=3.8.2",
    "pyyaml>=6.0.2",
    "requests>=2.32.4",
]
