# Note: this name should be changed;
# it will also require changing the Required Checks in the Branch Protection
name: Build and Push Docker Image

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
    # called from trigger-from-bazel-repo.yml
  workflow_dispatch:
    inputs:
        bazelCommitHash:
          description: 'The commit hash of the Bazel repo to use'
          type: string
          default: origin/main
  # allow debugging by triggering from the GitHub UI
  workflow_call:
    inputs:
        bazelCommitHash:
          description: 'The commit hash of the Bazel repo to use'
          type: string
          default: origin/main
jobs:
  # Like above, this name should be changed
  # It will also require changing the Required Checks in the Branch Protection
  docker-build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
        - uses: actions/checkout@v5
        - name: Checkout submodules
          run: git submodule update --init -- upstream
        
        - name: Checkout commit of BCR submodule
          working-directory: upstream
          run: git checkout ${{ inputs.bcrCommitHash }}

        - name: Clean up mdx files
          run: ./cleanup-mdx.sh

        - name: Transform upstream docs to mdx
          run: ./copy-upstream-docs.sh

        - name: Assert that nothing is different
          run: |
            if untracked=$(git status --porcelain | grep "^??"); then
                echo "Error: Untracked files found:"
                echo "$untracked"
                exit 1
            fi
            git diff --exit-code
