on:
  repository_dispatch:
    types: [on-bazel-trigger]
jobs:
  deploy:
    uses: ./.github/workflows/codegen.yml
    with:
      bcrCommitHash: ${{ github.event.client_payload.bcrCommitHash }}
      secrets: inherit
